# Generated by Django 5.2.8 on 2025-11-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('users', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', to='users.userprofile'),
        ),
    ]
